### ISSUE TITLE
Summarized Article File Existence Test Case

### ISSUE THREAD

**Issue by jzuri** [pgoodri/CS325_Project1#10]
Please implement a test function that runs the program with a set of URLs and verifies the existence of summarized article files in the Data/summarized directory. Assert that the files are created and contain the expected summarized content.

**Comment by pgoodri** [comment]
Done with inputting summarized article file existence test case, please review the code in test_cases.py

**Comment by jzuri** [comment]
Reviewed you code, everything looks good!
