### ISSUE TITLE
Invalid URL Test

### ISSUE THREAD

**Issue by pgoodri** [pgoodri/CS325_Project1#5]
Please create a test function that provides a URL that does not exist or is inaccessible in the input file. Assert that the program handles the invalid URL gracefully, perhaps by skipping it and proceeding with the next URL.

**Comment by jzuri** [comment]
Done with inputting Invalid URL Test, please review the code in test_cases.py

**Comment by pgoodri** [comment]
Reviewed. Everything looks good.
