### ISSUE TITLE
File Saving Test

### ISSUE THREAD

**Issue by pgoodri** [pgoodri/CS325_Project1#7]
Please write a test function that scrapes a known URL and saves the data to files using the file handler. Please assert that the files are created in the specified output directories (Data/processed, Data/raw, Data/summarized) and contain the expected content.

**Comment by jzuri** [comment]
Done with inputting a test case that preforms a file saving test, please review the code in test_cases.py

**Comment by pgoodri** [comment]
Reviewed. Everything looks good.
